"use client";

import React, { useState } from "react";
import { 
  Sparkles, Target, AlertTriangle, ShieldCheck, 
  HelpCircle, BookOpen, Clock, BarChart2,
  ChevronDown, ChevronUp, AlertCircle
} from "lucide-react";

interface Topic {
  concept: string;
  importance: "High" | "Medium" | "Low";
  explanation: string;
  likelyQuestion: string;
  tips: string;
  source: string;
  probabilityScore: number;
}

interface QuestionType {
  type: string;
  difficulty: "Easy" | "Medium" | "Hard";
  recommendedPractice: string;
}

interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  source: string;
}

interface CourseAnalysisData {
  summary: string;
  extracted_topics: any[];
  topic_frequency: any[];
  predicted_exam_topics: Topic[];
  question_bank: {
    quiz: QuizQuestion[];
    activeRecall: any[];
    definitions: any[];
    weakSpots: any[];
  };
  difficulty_breakdown: {
    difficultyLevels: {
      Easy: number;
      Medium: number;
      Hard: number;
    };
    recommendedPriority: string[];
  };
}

interface ExamPredictionSectionProps {
  analysis: CourseAnalysisData;
}

export default function ExamPredictionSection({ analysis }: ExamPredictionSectionProps) {
  const [expandedTopic, setExpandedTopic] = useState<number | null>(null);
  const [filterDifficulty, setFilterDifficulty] = useState<string>("All");

  const topics = analysis.predicted_exam_topics || [];
  const questionTypes = (analysis as any).questionTypes || [
    { type: "Multiple Choice Questions", difficulty: "Medium", recommendedPractice: "Drill key vocabulary & definitions" },
    { type: "Short Answer Calculations", difficulty: "Hard", recommendedPractice: "Solve past homework equations twice" },
    { type: "Trace & Debug Code", difficulty: "Hard", recommendedPractice: "Dry run pointers on paper" }
  ];
  
  const quizzes = analysis.question_bank?.quiz || [];
  const definitions = analysis.question_bank?.definitions || [];

  const getProbabilityColor = (score: number) => {
    if (score >= 85) return "from-rose-500 to-orange-500 text-rose-600 border-rose-200 bg-rose-50";
    if (score >= 70) return "from-amber-500 to-yellow-500 text-amber-600 border-amber-200 bg-amber-50";
    return "from-blue-500 to-sky-500 text-blue-600 border-blue-200 bg-blue-50";
  };

  const getDifficultyColor = (diff: string) => {
    switch (diff) {
      case "Hard": return "bg-rose-50 text-rose-700 border-rose-100";
      case "Medium": return "bg-amber-50 text-amber-700 border-amber-100";
      default: return "bg-emerald-50 text-emerald-700 border-emerald-100";
    }
  };

  return (
    <div className="space-y-6">
      
      {/* ⚠️ Disclaimer Banner */}
      <div className="p-4 rounded-xl border border-amber-200 bg-amber-50/70 text-amber-900 text-xs flex items-start gap-3">
        <AlertTriangle className="h-4.5 w-4.5 text-amber-600 shrink-0 mt-0.5" />
        <div className="leading-relaxed">
          <span className="font-bold">Important Notice & Disclaimer:</span>
          <p className="mt-0.5 text-amber-800">
            This final exam prediction is generated by AI models analyzing your uploaded files. Probability scores are statistical estimations based on lecture details and syllabus weights. These are study prioritization recommendations only and <span className="font-semibold underline">do not guarantee</span> specific exam patterns, topics, or passing grades.
          </p>
        </div>
      </div>

      {/* Course Summary Insight */}
      <div className="quill-card p-5 border border-slate-200 rounded-2xl bg-white shadow-sm space-y-2">
        <div className="flex items-center gap-2">
          <BookOpen className="h-4.5 w-4.5 text-blue-600" />
          <h3 className="text-sm font-bold text-slate-800">Course Final Exam Profile</h3>
        </div>
        <p className="text-xs text-slate-500 leading-relaxed">
          {analysis.summary}
        </p>
      </div>

      {/* 1. High Probability Topics */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4.5 w-4.5 text-blue-600 animate-pulse" />
            <h3 className="text-sm font-bold text-slate-800">High Probability Topics</h3>
          </div>
          <span className="text-[10px] text-slate-400 font-semibold bg-slate-100 px-2 py-0.5 rounded-full">
            {topics.length} Predicted Topics
          </span>
        </div>

        <div className="grid gap-3">
          {topics.map((topic, idx) => {
            const isExpanded = expandedTopic === idx;
            const probColorClass = getProbabilityColor(topic.probabilityScore || 0);

            return (
              <div 
                key={idx}
                className="border border-slate-200 bg-white rounded-xl overflow-hidden hover:shadow-md transition-all duration-200"
              >
                {/* Header Row */}
                <div 
                  onClick={() => setExpandedTopic(isExpanded ? null : idx)}
                  className="flex items-center justify-between p-4 cursor-pointer select-none"
                >
                  <div className="flex items-center gap-3.5 min-w-0 pr-4">
                    {/* Circle Score dial */}
                    <div className="relative w-11 h-11 shrink-0 flex items-center justify-center rounded-full bg-slate-50 border border-slate-100 shadow-inner">
                      <span className="text-xs font-extrabold font-mono text-slate-850">
                        {topic.probabilityScore || 50}%
                      </span>
                    </div>

                    <div className="min-w-0">
                      <span className="text-[9px] font-bold text-slate-400 uppercase tracking-wide">
                        Ref: {topic.source || "Course Notes"}
                      </span>
                      <h4 className="text-sm font-bold text-slate-800 truncate">
                        {topic.concept}
                      </h4>
                    </div>
                  </div>

                  <div className="flex items-center gap-3">
                    <span className={`px-2 py-0.5 rounded text-[9px] font-bold uppercase border tracking-wider ${probColorClass}`}>
                      {topic.importance} Importance
                    </span>
                    {isExpanded ? <ChevronUp className="h-4 w-4 text-slate-400" /> : <ChevronDown className="h-4 w-4 text-slate-400" />}
                  </div>
                </div>

                {/* Expanded content */}
                {isExpanded && (
                  <div className="px-4 pb-4 pt-1.5 border-t border-slate-100 bg-slate-50/30 space-y-3.5 text-xs">
                    <div>
                      <span className="text-[9px] font-bold text-slate-400 uppercase tracking-wide block mb-1">Why it is highly likely to be tested</span>
                      <p className="text-slate-650 leading-relaxed">{topic.explanation}</p>
                    </div>

                    <div className="p-3 bg-white border border-slate-200 rounded-xl">
                      <span className="text-[9px] font-bold text-blue-600 uppercase tracking-wide block mb-1.5">Likely Exam Question Pattern</span>
                      <pre className="text-slate-755 font-mono text-[10px] whitespace-pre-wrap leading-relaxed">
                        {topic.likelyQuestion}
                      </pre>
                    </div>

                    <div className="flex items-start gap-1.5 text-[10px] text-slate-550 italic bg-blue-50/50 p-2.5 rounded-lg border border-blue-100/50">
                      <ShieldCheck className="h-3.5 w-3.5 text-blue-500 shrink-0 mt-0.5" />
                      <span><strong>AI Strategy Tip:</strong> {topic.tips}</span>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* 2. Predicted Question Types & Difficulty */}
      <div className="grid md:grid-cols-5 gap-4">
        
        {/* Difficulties summary */}
        <div className="md:col-span-2 quill-card p-5 border border-slate-200 bg-white rounded-2xl space-y-4">
          <div className="flex items-center gap-2 border-b border-slate-100 pb-2">
            <BarChart2 className="h-4 w-4 text-blue-600" />
            <h3 className="text-xs font-bold text-slate-800 uppercase tracking-wider">Difficulty Breakdown</h3>
          </div>

          <div className="space-y-3.5">
            <div>
              <div className="flex justify-between text-xs font-semibold mb-1">
                <span className="text-rose-600">Hard Questions</span>
                <span className="text-slate-600 font-mono">
                  {analysis.difficulty_breakdown?.difficultyLevels?.Hard || 0} topics
                </span>
              </div>
              <div className="w-full h-1.5 bg-slate-100 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-rose-500" 
                  style={{ width: `${((analysis.difficulty_breakdown?.difficultyLevels?.Hard || 0) / Math.max(1, topics.length)) * 100}%` }}
                />
              </div>
            </div>

            <div>
              <div className="flex justify-between text-xs font-semibold mb-1">
                <span className="text-amber-600">Medium Questions</span>
                <span className="text-slate-600 font-mono">
                  {analysis.difficulty_breakdown?.difficultyLevels?.Medium || 0} topics
                </span>
              </div>
              <div className="w-full h-1.5 bg-slate-100 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-amber-500" 
                  style={{ width: `${((analysis.difficulty_breakdown?.difficultyLevels?.Medium || 0) / Math.max(1, topics.length)) * 100}%` }}
                />
              </div>
            </div>

            <div>
              <div className="flex justify-between text-xs font-semibold mb-1">
                <span className="text-emerald-600">Easy Questions</span>
                <span className="text-slate-600 font-mono">
                  {analysis.difficulty_breakdown?.difficultyLevels?.Easy || 0} topics
                </span>
              </div>
              <div className="w-full h-1.5 bg-slate-100 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-emerald-500" 
                  style={{ width: `${((analysis.difficulty_breakdown?.difficultyLevels?.Easy || 0) / Math.max(1, topics.length)) * 100}%` }}
                />
              </div>
            </div>
          </div>
        </div>

        {/* Question Types List */}
        <div className="md:col-span-3 quill-card p-5 border border-slate-200 bg-white rounded-2xl space-y-3.5">
          <div className="flex items-center gap-2 border-b border-slate-100 pb-2">
            <HelpCircle className="h-4 w-4 text-blue-600" />
            <h3 className="text-xs font-bold text-slate-800 uppercase tracking-wider">Likely Question Styles</h3>
          </div>

          <div className="space-y-2.5">
            {questionTypes.map((q: any, idx: number) => (
              <div key={idx} className="p-3 border border-slate-150 rounded-xl bg-slate-50/50 flex items-center justify-between gap-3 text-xs">
                <div>
                  <h4 className="font-bold text-slate-800">{q.type}</h4>
                  <p className="text-slate-450 text-[10px] mt-0.5">Focus: {q.recommendedPractice}</p>
                </div>
                <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase border shrink-0 ${getDifficultyColor(q.difficulty)}`}>
                  {q.difficulty}
                </span>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* 3. Must-Review Questions */}
      <div className="quill-card p-5 border border-slate-200 bg-white rounded-2xl space-y-4">
        <div className="flex items-center justify-between border-b border-slate-150 pb-2.5">
          <div className="flex items-center gap-2">
            <Target className="h-4.5 w-4.5 text-blue-600" />
            <h3 className="text-sm font-bold text-slate-800">Must-Review Exercises</h3>
          </div>

          <div className="flex gap-1">
            {["All", "Quiz Questions", "Core Definitions"].map((filter) => (
              <button
                key={filter}
                onClick={() => setFilterDifficulty(filter)}
                className={`px-2.5 py-1 text-[10px] font-bold rounded-lg transition-colors cursor-pointer ${
                  filterDifficulty === filter
                    ? "bg-blue-600 text-white"
                    : "bg-slate-100 text-slate-500 hover:bg-slate-200"
                }`}
              >
                {filter}
              </button>
            ))}
          </div>
        </div>

        <div className="space-y-3 max-h-[300px] overflow-y-auto pr-1">
          {filterDifficulty !== "Core Definitions" && quizzes.map((q, idx) => (
            <div key={`q-${idx}`} className="p-3 border border-slate-150 rounded-xl bg-slate-50/30 text-xs hover:border-blue-300 transition-colors">
              <div className="flex items-center justify-between gap-2 border-b border-slate-100 pb-1 mb-2">
                <span className="px-1.5 py-0.2 rounded bg-amber-50 border border-amber-200 text-amber-600 font-bold text-[9px]">
                  PRACTICE QUIZ Q{idx + 1}
                </span>
                <span className="text-[9px] font-mono text-slate-400">Source: {q.source}</span>
              </div>
              <p className="font-bold text-slate-750">{q.question}</p>
              <p className="text-slate-500 mt-1 italic text-[10px]">Explanation: {q.explanation}</p>
            </div>
          ))}

          {filterDifficulty !== "Quiz Questions" && definitions.map((d, idx) => (
            <div key={`d-${idx}`} className="p-3 border border-slate-150 rounded-xl bg-slate-50/30 text-xs hover:border-blue-300 transition-colors">
              <div className="flex items-center justify-between gap-2 border-b border-slate-100 pb-1 mb-2">
                <span className="px-1.5 py-0.2 rounded bg-blue-50 border border-blue-200 text-blue-600 font-bold text-[9px]">
                  CONCEPT CARD
                </span>
                <span className="text-[9px] font-mono text-slate-400">Source: {d.source}</span>
              </div>
              <p className="font-bold text-slate-850">{d.term}</p>
              <p className="text-slate-600 mt-1 text-[11px] leading-relaxed">{d.definition}</p>
              {d.formula && (
                <div className="mt-2 p-1.5 bg-white border border-slate-150 font-mono text-[10px] text-blue-650 rounded">
                  {d.formula}
                </div>
              )}
            </div>
          ))}

          {((filterDifficulty === "All" && quizzes.length === 0 && definitions.length === 0) ||
            (filterDifficulty === "Quiz Questions" && quizzes.length === 0) ||
            (filterDifficulty === "Core Definitions" && definitions.length === 0)) && (
            <p className="text-center text-xs text-slate-400 py-6">No questions found in this category.</p>
          )}
        </div>
      </div>

    </div>
  );
}
