import { StudyPack } from "./demoData";

/**
 * Converts a StudyPack object to a beautiful, structured Markdown document
 * optimized for Notion import.
 */
export function generateMarkdown(pack: StudyPack): string {
  let md = `# CoursePack AI: ${pack.courseCode} - ${pack.courseName}\n`;
  md += `**University:** ${pack.university}\n\n`;
  md += `> [!NOTE]\n`;
  md += `> **Course Summary:** ${pack.summary}\n\n`;
  
  md += `## 🗺️ Course Map\n\n`;
  md += `| Period | Topic | Key Concepts | Weight | Source |\n`;
  md += `| :--- | :--- | :--- | :--- | :--- |\n`;
  pack.courseMap.forEach((item) => {
    md += `| ${item.week} | ${item.topic} | ${item.concepts.join(", ")} | ${item.weight} | ${item.source} |\n`;
  });
  md += `\n`;

  md += `## 🎯 Exam Focus & High-Priority Areas\n\n`;
  pack.examFocus.forEach((item, index) => {
    md += `### ${index + 1}. ${item.concept} [Priority: ${item.importance}]\n`;
    md += `* **Source:** ${item.source}\n`;
    md += `* **Why it matters:** ${item.explanation}\n`;
    md += `* **Likely Exam Question:** \n`;
    md += `  \`\`\`text\n  ${item.likelyQuestion}\n  \`\`\`\n`;
    md += `* **Preparation Tip:** ${item.tips}\n\n`;
  });

  md += `## 📖 Core Definitions & Formulas\n\n`;
  pack.definitions.forEach((item) => {
    md += `<details>\n`;
    md += `<summary><b>${item.term}</b> (Source: ${item.source})</summary>\n\n`;
    md += `* **Definition:** ${item.definition}\n`;
    if (item.formula) {
      md += `* **Formula/Syntax:** \`${item.formula}\`\n`;
    }
    if (item.confusionPoint) {
      md += `* **Watch out for:** ${item.confusionPoint}\n`;
    }
    md += `\n</details>\n\n`;
  });

  md += `## 🧠 Active Recall Self-Test\n\n`;
  pack.activeRecall.forEach((item, index) => {
    md += `### Q${index + 1}: ${item.question}\n`;
    md += `* **Source:** ${item.source}\n`;
    md += `* **Hint:** *${item.hint}*\n`;
    md += `<details>\n<summary>Reveal Answer</summary>\n\n${item.answer}\n\n</details>\n\n`;
  });

  md += `## 📝 Practice Quiz\n\n`;
  pack.quiz.forEach((item, index) => {
    md += `### Q${index + 1}: ${item.question}\n`;
    md += `* **Source:** ${item.source}\n`;
    item.options.forEach((opt, idx) => {
      md += `* [ ] ${opt}\n`;
    });
    md += `<details>\n<summary>Reveal Correct Answer & Explanation</summary>\n\n`;
    md += `**Correct Answer:** Option ${item.correctAnswer + 1} (${item.options[item.correctAnswer]})\n\n`;
    md += `**Explanation:** ${item.explanation}\n\n`;
    md += `</details>\n\n`;
  });

  md += `## ⚠️ My Weak Spots (To Focus On)\n\n`;
  md += `| Concept | Context & Weight | Action Plan | Source |\n`;
  md += `| :--- | :--- | :--- | :--- |\n`;
  pack.weakSpots.forEach((item) => {
    md += `| **${item.concept}** | ${item.coverage} | ${item.action} | ${item.source} |\n`;
  });
  md += `\n`;

  md += `## 📅 7-Day Cram Plan\n\n`;
  pack.sevenDayPlan.forEach((item) => {
    md += `### 🗓️ Day ${item.day}: ${item.focus}\n`;
    item.tasks.forEach((task) => {
      md += `- [ ] ${task}\n`;
    });
    md += `\n`;
  });

  md += `\n---\n*Generated by CoursePack AI - Upload your course materials. Get a study pack in 3 minutes.*`;
  return md;
}

/**
 * Converts the active recall items to an Anki-importable Tab-Separated Values (TSV) string.
 */
export function generateAnkiCSV(pack: StudyPack): string {
  // Anki deck format: Front \t Back \t Tags (optional)
  // We double-quote values and escape inner quotes to ensure safe CSV parsing.
  let csv = "#separator:tab\n#html:true\n#tags column:3\n";
  
  // 1. Add active recall items
  pack.activeRecall.forEach((item) => {
    const front = `<div style="font-family: Arial; font-size: 18px; color: #1e293b;"><b>[Recall]</b> ${item.question}</div><div style="font-size: 12px; color: #64748b; margin-top: 8px;">Source: ${item.source}</div>`;
    const back = `<div style="font-family: Arial; font-size: 16px; color: #0f172a;">${item.answer}</div><div style="font-size: 12px; color: #94a3b8; font-style: italic; margin-top: 8px;">Hint: ${item.hint}</div>`;
    const tag = `${pack.courseCode.replace(/\s+/g, "_")}_recall`;
    csv += `"${front.replace(/"/g, '""')}"\t"${back.replace(/"/g, '""')}"\t"${tag}"\n`;
  });

  // 2. Add definition items
  pack.definitions.forEach((item) => {
    const front = `<div style="font-family: Arial; font-size: 18px; color: #1e293b;"><b>[Definition]</b> What is <b>${item.term}</b>?</div><div style="font-size: 12px; color: #64748b; margin-top: 8px;">Source: ${item.source}</div>`;
    let back = `<div style="font-family: Arial; font-size: 16px; color: #0f172a;">${item.definition}</div>`;
    if (item.formula) {
      back += `<div style="font-family: monospace; background: #f1f5f9; padding: 6px; border-radius: 4px; margin-top: 8px; font-size: 14px;">${item.formula}</div>`;
    }
    if (item.confusionPoint) {
      back += `<div style="font-size: 13px; color: #b91c1c; font-weight: bold; margin-top: 8px;">⚠️ Common Mistake:</div><div style="font-size: 13px; color: #374151;">${item.confusionPoint}</div>`;
    }
    const tag = `${pack.courseCode.replace(/\s+/g, "_")}_definitions`;
    csv += `"${front.replace(/"/g, '""')}"\t"${back.replace(/"/g, '""')}"\t"${tag}"\n`;
  });

  return csv;
}

/**
 * Utility to trigger browser download of a text file
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
